### PR TITLE
Deleting tracks bug in the program builder #3710

### PR DESCRIPTION
**Pull request by naazy**
Deleting tracks bug in the program builder https://github.com/OxfordAbstracts/application/issues/3710

### CODE REVIEW

**Comment by naazy** [comment]
Ready to review @roryc89. The tests are actually passing it's just there's something up with Circle CI

**Comment by roryc89** [comment]
looks good :)

**Comment by nelsonic** [comment]
@naazy can you make CI happy? 🤔

**Comment by naazy** [comment]
No luck getting this to pass CI yet

**Pull request closed without merging**
