### PR TITLE
Individual scheduling #3433

### PR DESCRIPTION
**Pull request by roryc89**
addresses https://github.com/OxfordAbstracts/application/issues/3433

### CODE REVIEW

**Comment by roryc89** [comment]
Ci tests do not appear to work but all tests pass locally

**Comment by naazy** [comment]
The add new time button should not be green because it's not a primary action (it should be mint). it should look like:
screen shot 2017-07-14 at 10 53 53

**Comment by roryc89** [comment]
Yes good point on the tertiary buttons. I would see the preventing of saving start times as later than end times as a nice to have enhancement we can add if requested. It doesn't break the UI like it does with sessions.

**Comment by naazy** [comment]
True it's an 'enhancement' but I think that because we have validation for the rest of the edit session section (as requested by OA), they would expect it for this too?

**Comment by roryc89** [comment]
I haven't seen a requirement for this. But I'll call up @Boatlaunch101 and see if they'd like it.

**Comment by roryc89** [comment]
They are happy to proceed without it.

**Comment by naazy** [comment]
Over to view @SimonLab

**Comment by SimonLab** [comment]
Code looks good :+1: @naazy do you mind to merge this PR I don't have the right to do it on this repo

**Comment by Boatlaunch101** [comment]
@naazy @SimonLab not sure if this is relevant but we want to do a deployment this morning so no Please tests just for the moment please.

**Comment by naazy** [comment]
Merging @SimonLab and I'll make you an admin now. @Boatlaunch101 don't worry - merging this PR won't affect master until https://github.com/OxfordAbstracts/application/pull/3548 has been merged in (which we will pause for now)

**Pull request merged**
